### ISSUE TITLE
Provide integration for Datadog 

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/integrations#23]
Similar to the integrations that are already existing for [Prometheus](https://github.com/keptn-contrib/prometheus-sli-service) and [Dynatrace](https://github.com/keptn-contrib/dynatrace-sli-service), an SLI provider for Datadog is desired.

**Desired solution**
It should able to fetch data from Datadog for Keptn quality gates. Doing so, the service should be able to retrieve the values of SLIs from a Datadog tenant via the Datadog API. For that, it has to handle the Keptn Event `sh.keptn.internal.event.get-sli` which gets executed as part of a quality gate evaluation.

An example of an SLI file is shown below:
```
---
spec_version: '1.0'
indicators:
  response_time_p95: datadog API query goes here
  error_rate: datadog API query goes here
```

An example on how to get started, I'll refer to some steps highlighted in a [blog article](https://www.neotys.com/blog/neotyspac-automate-test-analysis-custom-keptn-sli-provider-andreas-grabner/) from @grabnerandi :
1. Clone the template repo: https://github.com/keptn-sandbox/keptn-service-template-go/
1. Replace the template name placeholders with your data provider name
1. Implement the method `HandleInternalGetSLIEvent` in `eventhandlers.go`
1. Run the test suite to validate that your code works
1. Build the container, push it to Dockerhub and let the Keptn community know!

![image](https://user-images.githubusercontent.com/7677092/98535004-a8a03b00-2285-11eb-90d1-073ac34ce3d5.png)

For details on how to calculate the values for the SLIs, the [Datadog documentation](https://docs.datadoghq.com/api/v1/metrics/#query-timeseries-points) should be consulted.

The service should be contributed to the Keptn-Sandbox organization, but for the sake of a better overview, I opened the issue in this organization. 

**Definition of Done**

- [x] repo created in the keptn-sandbox organization and code contributed to this repo
- [ ] images pushed to keptnsandbox organization on dockerhub (this is already prepared if you are using the template https://github.com/keptn-sandbox/keptn-service-template-go/ )
- [x] services listens to `sh.keptn.internal.event.get-sli` and retrieves values for SLI from Datadog
- [x] services sends the list of SLIs as a `sh.keptn.internal.event.get-sli.done` event (see [spec](https://github.com/keptn/spec/blob/master/cloudevents.md#get-sli-done))
- [ ] A tutorial is added to https://tutorials.keptn.sh/ . [Contributing Tutorials](https://github.com/keptn/tutorials/tree/master/site/tutorials#write-your-tutorial)

**Comment by agardnerIT** [comment]
@vadasambar what's the status of this? I see datadog is listed as experimental in the `keptn configure monitoring` CLI command. However this integration is not yet listed here: https://keptn.sh/docs/integrations/ (would greatly help with visibility.

If this SLI provider has a commitment to be actively supported by the community then I can show you what files you need to create to get it listed on the above page. Let me know :)

**Comment by vadasambar** [comment]
> @vadasambar what's the status of this? I see datadog is listed as experimental in the `keptn configure monitoring` CLI command. However this integration is not yet listed here: https://keptn.sh/docs/integrations/ (would greatly help with visibility.
> 
> If this SLI provider has a commitment to be actively supported by the community then I can show you what files you need to create to get it listed on the above page. Let me know :)

The integration is in working state but we haven't:
1. Added it to https://keptn.sh/docs/integrations/ yet
2. I think we also need to set up the wiring to push the helm chart to artifacthub
3. I have to write a tutorial on how to use the integration for our docs site
For 1 and 2, I guess I will need yours and maybe Oleg's help to set up the wiring and put it on the https://keptn.sh/docs/integrations/ page. 

For 3, I am trying to come up with a good example for showcasing how the integration works.

**Comment by agardnerIT** [comment]
Happy to help here.

1. Is now done: https://github.com/keptn-contrib/artifacthub/tree/main/datadog-service/0.15.0
2. We don't currently auto build helm charts from keptn-contrib or keptn-sandbox
3. Happy to help here. I think quality gates is the perfect usecase

**Comment by vadasambar** [comment]
> We don't currently auto build helm charts from keptn-contrib or keptn-sandbox

:memo: 

> Happy to help here. I think quality gates is the perfect usecase

I am thinking of something along those lines as well. Will reach out to you if I need help. Thank you.
